{% set name = "analysis" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}
{% set micro = "" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}{{ micro }}

build:
  skip: True  # [py<37]
  number: 9

requirements:
  host:
    - python
  run:
    - python
    - amostra <=1.0
    - area-detector-handlers
    - arvpyf
    - attrs >=18.0
    - black
    - bluesky >=1.6.5
    - bluesky-kafka  # [not win]
    - boto3
    - conda-pack
    - dask
    - databroker >=1.0.6
    - databroker-pack
    - distributed
    - event-model >=1.15.2
    - fabio
    - ffmpeg >=4.0
    - flake8
    - graphviz
    - grid-strategy
    - h5py >=2.9.0
    - hdf5-lz4  # [not win]
    - ipykernel
    - ipympl ==0.1.1
    - ipython
    - ipywidgets ==7.2.1
    - isort
    - jupyter
    - jupyterlab
    - line_profiler
    - lmfit
    - lxml
    - matplotlib >=3.1.0
    - memory_profiler
    - mendeleev
    - modestimage
    - napari >=0.3.5
    - natsort
    - netcdf4
    - nexpy >=0.12.6
    - nodejs
    - numexpr
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.5.2
    - oscars
    - papermill
    - peakutils
    - periodictable
    - photutils
    - pycentroids  # [not win]
    - pyepics >=3.4.2
    - pyfai
    - pyfftw
    - pymongo >=3.7
    - pypdf2
    - pyqt >=5.9.0
    - pystackreg
    - python-graphviz
    - pyxrf >=0.0.31
    - pyzbar  # [not win]
    - qt >=5.9.0
    - reportlab
    - sasview
    - scikit-beam >=0.0.21
    - scikit-learn
    - scipy
    - srw  # [linux]
    - suitcase-csv
    - suitcase-json-metadata
    - suitcase-jsonl
    - suitcase-mongo
    - suitcase-msgpack
    - suitcase-specfile
    - suitcase-tiff
    - suitcase-utils
    - sympy
    - toml
    - tomopy
    - tornado
    - tqdm
    - tzlocal >=1.5
    - xlrd
    - xlwt
    - xray-vision
    - xraylarch

test:
  requires:
    - nsls2forge-utils
  imports:
    - area_detector_handlers
    - bluesky
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - napari
    - numpy
    - ophyd
    - oscars
    - peakutils
    - photutils
    - pymongo
    - pyxrf
    - skbeam
    - srwlpy  # [linux]
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
  commands:
    # Fail if the "conda-forge" channel is in the list of channels.
    - check-results -t channels -f conda-forge
    # Fail if versions of the packages are not as expected minimum ones.
    - check-results -t version -p bluesky    -e 1.6
    - check-results -t version -p databroker -e 1.0
    - check-results -t version -p ophyd      -e 1.5
    - python -V
    - ipython -V
    - nexpy --help
    - napari --help
    - napari --version

about:
  home: https://nsls-ii.github.io/deployment_docs.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Analysis metapackage for NSLS-II deployments
  description: |
    Analysis metapackage for NSLS-II deployments. See the deployment
    documentation at https://nsls-ii.github.io/deployment_docs.html.
